### PR TITLE
Modified syco include path

### PR DESCRIPTION
**Pull request by arlukin**
Include the common folder at the first position in include path, instead of the last. The result of this will be that when we import mysql.py it will be picked from the common folder instead of the regular python library folders.

### CODE REVIEW

**Comment by arlukin** [comment]
@kribor Tror du det blir mer problem med fixen än vad den fixar?

**Comment by arlukin** [comment]
@kribor Have you seen this pull req?

**Comment by kribor** [comment]
Does this solve a problem that you found or why did you implement this change?

I think the change makes sense for syco since it's not focused on having unique namespaces and the use of the standard python libraries is limited. 

How much did you test this?

**Comment by arlukin** [comment]
It was Martin that had problem with this. The server he was using syco on had the mysql pip package installed. And syco found that mysql file instead of the syco module mysql.

We basically just tested it on that server, and i tested it in my sandbox.

**Pull request merged**
