### PR TITLE
Install for ruby 2.2.2

### PR DESCRIPTION
**Pull request by muzicaed**

### CODE REVIEW

**Comment by kribor** [comment]
If this installation should go into the systemconsole base, maybe the rpm should be in a repo under systemconsole as well?

**Comment by kribor** [comment]
Oh, and another question, are we legally allowed to redistribute ruby? :P

**Comment by muzicaed** [comment]
Hum, not that good at reading github comments :) 
I will move the rpm to systemconsole. 
And when it comes to legal it should not be a problem: Ruby is "copylefted" but with an added " "in the Public Domain or otherwise ... Freely Available", and as publish this Public without charge it should be safe.

**Comment by kribor** [comment]
ping

**Comment by arlukin** [comment]
Closed by arlukin, probably outdated.

**Pull request closed without merging**
